name: Build Vuepress and Sync Gitee
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm i

    # Vuepress Build.
    - name: Generates Pages
      run: |
        npm run build

    - name: Deploy Github PagesğŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        repository-name: toimc/notes-page # The branch the action should deploy to.
        branch: master
        folder: ./src/.vuepress/dist # The folder the action should deploy.
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Sync to Gitee Page
      uses: wearerequired/git-mirror-action@master
      env:
        # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PRIVATE_KEY
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
        # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ GitHub æºä»“åº“åœ°å€
        source-repo: git@github.com:toimc/notes-page.git
        # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç›®æ ‡ä»“åº“åœ°å€
        destination-repo: git@gitee.com:toimc/notes-page.git

    - name: Trigger Gitee Pages Auto Reload
      uses: yanglbme/gitee-pages-action@master
      with:
        # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
        gitee-username: toimc
        # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“ï¼Œä»“åº“åä¸¥æ ¼åŒºåˆ†å¤§å°å†™ï¼Œè¯·å‡†ç¡®å¡«å†™ï¼Œå¦åˆ™ä¼šå‡ºé”™
        gitee-repo: toimc/notes-page